### ISSUE TITLE
Licenças

### ISSUE THREAD

**Issue by alexandre-mbm** [OSMBrasil/IJSN_road_import#1]
- [x] [scripts/upload/*.py](../tree/master/scripts/upload) declaram-se sob GPL mas falta o arquivo de licença
- [x] [scripts/shp2osm/*](../tree/master/scripts/shp2osm) não declaram licença
  - Não se deve "presumir" GPLv2 ou qualquer licença que não o _copyright_ tradicional, tal como está acontecendo em [scripts/shp2osm/README.md#LICENSE](../blob/master/scripts/shp2osm/README.md#License); é preciso sanar aquela indeterminação
    - Ebner já nos respondeu que o arquivo dele pode ser sob GPLv2
- [x] [import/](../tree/master/import) não declara licenças
  - A issue #3 foi atribuída a @willemarcel: "Aplicar licença [GPLv2] a import/convert_shapes.sh"
- [x] Cada um desses diretórios pode conter seu README.md para se autoexplicar
- [x] @OSMBrasil/owners, todos concordam em não apressar [/LICENSE](../blob/master/LICENSE) com GPLv2? Vejo isso como uma medida de segurança, para evitar embaraços com compatibilidade entre licenças diferentes

**Comment by Skippern** [comment]
certo, vou resolver quando #2 e resolvido, no momento tudo travado aqui porque não consigo sincronizar arquivos grandes pelo meu linha limitado

**Comment by Skippern** [comment]
Ja dicionei `LICENSE` no arquivo principal (`/`), `import/` e `scripts/upload`. Vou fazer um README para cada pasta no `script/` com descrição onde ha os originais.

**Comment by Skippern** [comment]
@alexandre-mbm Bom assim?

**Comment by alexandre-mbm** [comment]
Talvez seja melhor deixar o LICENSE de GPL v2 somente onde já é esta licença. Pois talvez se queira usar outros scripts em outras licenças. Deixar a GPL no `/`, por exemplo, pode confundir, por causa disso. Esta licença só é viral, logicamente, para trabalhos derivados ou muito acoplados.

**Comment by Skippern** [comment]
Alexandre: Eu nao tem este arquivo disponível, e meu coneção internet e lerdo, voce pode substitui o arquivo no `/`?

**Comment by alexandre-mbm** [comment]
Que arquivo? O respositório está com alguns poucos Kbytes, apenas.

Eu só estou **sugerindo** que vocês **não** apliquem GPLv2 para tudo. Mas se querem assim, não é necessário ter um LICENSE em cada subdiretório. **Façam como quiserem.**

De um modo ou de outro, seja com uma generalização no `/`, seja com especializações em cada subdiretório ou código fonte de script, é preciso deixar claro sob qual licença aquilo está.

**Comment by Skippern** [comment]
O que queria dizer e não ha internet para procura arquivo LICENSE em outro versão, se voce acho melhor coloque arquivo LICENSE do GPL (sem versão) no pasta principal, então algum outro deve fazer.

Eu coloquei este arquivo LICENSE porque achei no outros projetos que tem no computador. (ps. to dividindo um linha 1024k com 300 pessoas, não ha muito sobrando p cada)

**Comment by alexandre-mbm** [comment]
@Skippern, primeiro: não sinta-se pressionado a atender minhas "demandas".

Mas a questão principal que estou trazendo não é aplicar uma licença qualquer. É aplicar **a licença correta de cada peça de software**. Se usamos código de um fulano, que esse fulano liberou sob GPLv2, aquela peça tem de estar aqui sob GPLv2. Se @willemarcel escreveu um script e publicou aqui sem licença, a responsibilidade e o interesse maior de aplicar uma licença a aquele script, é dele. Por outro lado, se vocês conseguirem gerenciar que tudo vem de código GPLv2, ou poderá ser GPLv2, e vocês querem assim, então, **em comum acordo**, a licença pode ser anunciada para todo o repositório. Porém, é preciso ter cuidado com compatibilidade de licenças. Minha abordagem centra-se em chamar a atenção para isso. Não é simplesmente copiar um texto jurídico qualquer em vários locais.

**Comment by Skippern** [comment]
Isso e um assunto eu não intendo muito bem.

Para mim meu código e um licença aberta. Algum que sabe este assunto melhor pode melhorar isso. Para mim, deixo assim por enquanto, e se algum quer ou preciso mudar isso por qualquer motivo esta bom. Os principais e que este projeto deve ser aberto, se usamos scripts dos outros projetos (como no pasta `scripts/`) anunciamos este com o licença certo deles.

**Comment by alexandre-mbm** [comment]
Eu vejo que este repositório pode conter scripts em várias licenças. É preciso respeitar as licenças de código que não é nosso. E vejo que o membros participantes deste projeto podem ir licenciando seus próprios scripts com licenças permissivas. Depois, lá na frente, pode ser aberta uma discussão gerenciando e negociando lincenciamento, a fim de simplificá-lo.

@Skippern, deixe esta issue comigo, por enquanto.

**Comment by alexandre-mbm** [comment]
@Skippern, deixe essa issue comigo, por enquanto.

**Comment by alexandre-mbm** [comment]
- [x] @willemarcel, você decidiu uma licença para o que está em [import/](../tree/master/import)?
  - Respondeu por IRC que GPLv2 está OK
- [x] Vou iniciar um [tópico no fórum](http://forum.openstreetmap.org/viewtopic.php?id=30065), para o estudo/aprendizado de licenças.

**Comment by alexandre-mbm** [comment]
O [tópico no fórum](http://forum.openstreetmap.org/viewtopic.php?id=30065), com três referências iniciais, faz uma eficaz introdução às licenças de software de código aberto mais famosas. Estudemos por lá.

Notem que cada licença tem um modo de ser aplicada, restrição e permissividade.

**Comment by alexandre-mbm** [comment]
Hoje pela manhã eu enviei e-mail a autores dos arquivos de [scripts/shp2osm/](../tree/master/scripts/shp2osm/). A comunicação teve cópia para @Skippern.

Ebner já nos respondeu que o arquivo dele pode ser sob GPLv2. Mas eu ainda fiz pergunta se ele faria um pull request aplicando a licença. Sei que posso estar desejando demais, mas vejamos se acontece.

**Comment by alexandre-mbm** [comment]
Como declarei em IRC ontem, que eu ficaria **à frente** desta issue somente ontem e hoje, estou retirando minha **atribuição**. São 18h11 e passaram-se 24 horas. Tudo que é mais importante tem sido gerenciado por edição de minha primeira mensagem (lá em cima).

**Comment by alexandre-mbm** [comment]
Alexandre: Eu nao tem este arquivo disponível, e meu coneção internet e lerdo, voce pode substitui o arquivo no `/`?

**Comment by nighto** [comment]
WTFPL, se funciona bem para o iD, funciona bem pra gente. :-)
Em 13/02/2015 15:15, "Alexandre Magno" notifications@github.com escreveu:

**Comment by alexandre-mbm** [comment]
Eu admiro as intenções mais nobres que podemos imaginar estarem por trás de adoção da [WTFPL](http://en.wikipedia.org/wiki/WTFPL), mas eu realmente não acredito na validade jurídica dessa licença. Nem muito menos que ela possa ser segura para o próprio autor da obra. Em iniciativa que parta de mim (leia-se: **eu** criei algo e vou compartilhar com outras pessoas), vocês nunca me verão adotá-la. Não significa que não possam me ver contribuindo em projetos que já optaram por ela; essas são coisas muito diferentes.

Penso que cada um de nós é livre para licenciar suas próprias contribuições como quiser e conseguir. É interessante, num projeto como este, haver uma escolha norteadora. **Ou não.** Pois o que mais importa é um "gerenciamento de licenças", a compatibilidade de licenciamento entre os recursos.

**Comment by vgeorge** [comment]
Eu iria de licença MIT: 

http://choosealicense.com

**Comment by alexandre-mbm** [comment]
Penso que cada licença tem suas aplicações.

Em alguns projetos mais coletivos e menos acoplados, tal como numa coleção de _scripts_ independentes a serem usados num determinado contexto de atividades, cada autor pode estar muito desempendido — livre mesmo! — para escolher a licença de sua(s) contribuição(ões). Num projeto com tais características, a equipe facilmente também colhe e republica, respeitando a licença original, ferramentas criadas por autores externos.

**Sendo assim, minha opinião é:** que não declarem uma licença como "mestra" ou obrigatória para o [IJSN_road_import](OSMBrasil/IJSN_road_import). Não vale o esforço de discussão, e pode restringir muito. Especialmente uma licença _copyleft_ como a GPLv2, eu não vejo como "a melhor" para um projeto como este.

Se determinado _script_ fará realmente seu trabalho isoladamente, sem tornar-se dependência como **biblioteca** ou **utilitário** chave para outro software, não há problema algum em usar GPLv2 ou outro instrumento de _copyleft_ da preferência de seu autor.

_Copyleft_ foi a grande sacada do Stallman para obrigar o mundo a ter resultados altruístas. Mas também podemos acreditar que o mundo pode gestar e manter altruísmo sem a coação do _copyleft_.

**Comment by Skippern** [comment]
Apagando o `shp2osm` script, porque não seria utilizado, manipulamos nossos shapes com `ogr2ogr` e direitamente com `python`
