### ISSUE TITLE
Compartilhar shapefiles

### ISSUE THREAD

**Issue by Skippern** [OSMBrasil/IJSN_road_import#2]
Os shapefiles e bem grande e complicando **sync**

@willemarcel voce pode tira o shape do `import/` e mudar os scripts para rodar com os shapes no `shp/`

O pasta `shp/` e incluido no `.gitignore` e nao sincronizando.

No momento nao consigo sincronizar por caso do `Arruamento.zip`

**Comment by alexandre-mbm** [comment]
Os shapefiles precisam ser versionados? Vocês referem-se a resultados de processamento? Ainda que seja, é talvez interessante achar um lugar para fazer upload desses arquivos, **fora do git**, em algum FTP ou disco virtual, ou na nuvem. E se vocês falam de shapefiles originais, não modificados, melhor deixá-los na origem, disponibilizando listas de URLs para download com `wget`, ou script que propicie download parametrizado.

**Comment by Skippern** [comment]
Realmente os shapes não preciso ser verrinados ou nada, podemos armazinar o original do site no um pasta não sincronizada, e somente os scripts e o documentacao que preciso tracking e controle de version

**Comment by alexandre-mbm** [comment]
Talvez mesmo depois o que seja conveniente versionar seja apenas um histórico de "estados de comandos". Na verdade, um log que associe (1) shapefile original, (2) script, (3) seu commit de utilização e (4) linha de comando usada, os parâmetros passados.

Esse log poderia ser mantido manualmente em arquivos TXT, se fosse o caso. Ou script intermediário, fazendo como um pipe, poderia gerar a linha de log e empurrá-la para dentro dos tais TXT.

---

@Skippern, falo de algo como o que segue.

log.sh:

``` bash
#!/bin/bash
FILE="$1"
COMMIT=$(git rev-parse HEAD)
shift
echo "$COMMIT|$@" >> "$FILE"
$@
```

Usado assim (dentro de um repositório git):

``` console
$ ./log.sh my-file-of-log.txt echo "Hello World"
Hello World
```

Resulta em:

``` console
$ cat my-file-of-log.txt
2c150ddbc6e64c0e9d32939ee1199b80276167bf|echo Hello World
```

Pode-se acrescentar uma coluna de _datetime_.
Pode-se usar TAB invés de `|`. Ou fazer outro formato que não um CSV.

Note que infelizmente o registro de parâmetros do comando ficou sem aspas.

**Comment by willemarcel** [comment]
Pronto. Deletei o shape. Depois tento colocar em meu servidor. Tentei 
baixar com wget do site do IJSN e não consegui.

Em 2015-02-10 23:11, Aun Johnsen escreveu:

> Os shapefiles e bem grande e complicando SYNC
> 
> @willemarcel [1] voce pode tira o shape do import/ e mudar os scripts
> para rodar com os shapes no shp/
> 
> O pasta shp/ e incluido no .gitignore e nao sincronizando.
> 
> No momento nao consigo sincronizar por caso do Arruamento.zip
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [2].
> 
>   *
> 
> ## Links:
> 
> [1] https://github.com/willemarcel
> [2] https://github.com/OSMBrasil/IJSN_road_import/issues/2

## 

wille
http://wille.blog.br

**Comment by alexandre-mbm** [comment]
Sustento minha opinião acerca de _shapefiles vs. git_ ainda que vocês tenham esses problemas particulares. Não é interessante colocar no git grandes arquivos binários.

Sugiro até que combinem de fazer um rebase, apagando-os completamente do histórico. É preciso combinar porque após o rebase todos perdem o HEAD.

Quanto ao log.sh que exemplifico acima, é preciso notar que ele está muito simplificado, nem mesmo espera o sucesso do comando.  Outra modificação conveniente seria ele guardar um _hash_ MD5 do shapefile, afim de se poder rastrear minimamente mudanças nos resultados dos scripts.

**Comment by Skippern** [comment]
Se @willemarcel e @naoliv não tem objeções, pode sim, ja tem _backup_ do os arquivos no meu lado

@willemarcel confirma voce também tem backup, e algum que sabe como pode fazer o rebase.

Se precisamos compartilhar os shapes, podemos utilizar DropBox ou outro serviço de armazenamento

Pode também coloque os extensos do shapes no .gitignore para não compartilha-los

**Comment by willemarcel** [comment]
Pode fazer sim. Tenho backup. O ideal serial voltar pro último commit 
antes do meu.

Em 2015-02-11 12:57, Aun Johnsen escreveu:

> Se @willemarcel [1] e @naoliv [2] não tem objeções, pode sim, ja
> tem _backup_ do os arquivos no meu lado
> 
> @willemarcel [1] confirma voce também tem backup, e algum que sabe
> como pode fazer o rebase.
> 
> Se precisamos compartilhar os shapes, podemos utilizar DropBox ou
> outro serviço de armazenamento
> 
> Pode também coloque os extensos do shapes no .gitignore para não
> compartilha-los
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [3].
> 
>   *
> 
> ## Links:
> 
> [1] https://github.com/willemarcel
> [2] https://github.com/naoliv
> [3] 
> https://github.com/OSMBrasil/IJSN_road_import/issues/2#issuecomment-73905640

## 

wille
http://wille.blog.br

**Comment by alexandre-mbm** [comment]
Estou clonando o repositório para fazer o rebase. Compartilharei com vocês, aqui, o histórico de comandos para comunicar como foi. A priori, não vou reverter commits, apenas sumir com o shapefile.

**Comment by alexandre-mbm** [comment]
**Feito.** Estarei editando este comentário nos próximos instantes.

---

@willemarcel @Skippern 

# O rebase foi assim

Clonando o repositório:

``` console
$ git clone git@github.com:OSMBrasil/IJSN_road_import.git
Cloning into 'IJSN_road_import'...
Enter passphrase for key '/home/Alan/.ssh/id_rsa':
remote: Counting objects: 49, done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 49 (delta 16), reused 39 (delta 12)
Receiving objects: 100% (49/49), 13.57 MiB | 223.00 KiB/s, done.
Resolving deltas: 100% (16/16), done.
Checking connectivity... done.

$ cd IJSN_road_import/
```

Não era necessário ir até a raiz, mas como eram poucos commits, achei mais simples. Estou acostumado este comando:

``` console
$ git rebase -i --root
```

É realizada uma primeira etapa de processamento e abre-se o arquivo para a pessoa marcar ações. Marquei um único edit em commit:

```
pick 6706e0b README
pick e7dc382 .gitignore
pick 85f80d3 Scripts from svn.openstreetmap.org
edit b352bf8 add streets data and convert script
pick 44095c9 Minor edit on FILES.md and upload.py
pick 1911e68 Link to projections
pick 907a083 fix error
pick 89aacb0 Delete Arruamento.zip

# Rebase 89aacb0 onto 6e03333
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
```

Então pára-se para edição daquele commit, com instruções básicas:

``` console
$ git rebase -i --root
Stopped at b352bf8b26787554658b848b230f771c192e3a9d... add streets data and convert script
You can amend the commit now, with

        git commit --amend

Once you are satisfied with your changes, run

        git rebase --continue
```

Nesse momento, o commit ainda está inalterado:

``` console
$ git status
rebase in progress; onto 17cf3dc
You are currently editing a commit while rebasing branch 'master' on '17cf3dc'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

nothing to commit, working directory clean
```

Vamos apagar o arquivo:

``` console
$ cd import/
$ ls
Arruamento.zip  convert_shapes.sh

$ git rm Arruamento.zip
rm 'import/Arruamento.zip'
```

Agora o commit está alterado:

``` console
$ git status
rebase in progress; onto 17cf3dc
You are currently editing a commit while rebasing branch 'master' on '17cf3dc'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        deleted:    Arruamento.zip

git commit --amend
```

Vemos que o ammend faz o commit não ter mais o arquivo que o commit tinha antes:

```
add streets data and convert script

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Author:    Wille Marcel <wille@wille.blog.br>
# Date:      Tue Feb 10 22:39:54 2015 -0200
#
# rebase in progress; onto 17cf3dc
# You are currently editing a commit while rebasing branch 'master' on '17cf3dc'.
#
# Changes to be committed:
#       new file:   convert_shapes.sh
#
```

O resultado do comando acima é bem sucedido assim:

``` console
$ git commit --amend
[detached HEAD 273c9d9] add streets data and convert script
 Author: Wille Marcel <wille@wille.blog.br>
 Date: Tue Feb 10 22:39:54 2015 -0200
 1 file changed, 20 insertions(+)
 create mode 100644 import/convert_shapes.sh
```

Significa que o commit naquele ponto não cria mais o arquivo que apagamos.

Podemos continuar:

``` console
$ git rebase --continue
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git reset'
rebase in progress; onto 17cf3dc
You are currently rebasing branch 'master' on '17cf3dc'.

nothing to commit, working directory clean
Could not apply 89aacb0f92f80ceb6c7e779b736a0a5241940471... Delete Arruamento.zip
```

E como vemos acima, ele reclama que um commit (o último) apaga um arquivo que agora não existe mais. Eu desprezo isso e sigo em frente, com o propósito de reverter aquele commit depois ou fazer novo rebase só para rejeitá-lo. Só porque eu não sei a sintaxe para fazer diferente já nesse momento.

O editor abre com o aviso a seguir:

```
Delete Arruamento.zip
#
# It looks like you may be committing a cherry-pick.
# If this is not correct, please remove the file
#       .git/CHERRY_PICK_HEAD
# and try again.


# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Author:    Wille Marcel <wille@wille.blog.br>
# Date:      Wed Feb 11 08:39:04 2015 -0200
#
# rebase in progress; onto 17cf3dc
# You are currently rebasing branch 'master' on '17cf3dc'.
#
```

Isso enquanto o comando a seguir é processado:

``` console
$ git commit --allow-empty
[detached HEAD f46fcfd] Delete Arruamento.zip
 Author: Wille Marcel <wille@wille.blog.br>
 Date: Wed Feb 11 08:39:04 2015 -0200
```

Simplesmente seguimos em frente:

``` console
$ git status
rebase in progress; onto 17cf3dc
You are currently editing a commit while rebasing branch 'master' on '17cf3dc'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

nothing to commit, working directory clean

$ git rebase --continue
Successfully rebased and updated refs/heads/master.
```

**O rebase está concluído!**

Mas lembram daquele último commit? Agora vamos revertê-lo:

``` console
$ git reset --soft HEAD~1
```

As coisas assim é como eu as soube fazer, rapidamente, com sintaxes que eu já conhecia. É provável que exista um conjunto de comandos mais econômico para fazer a mesma coisa.

Este push terá de ser "forçado", porque todo o histórico está com hashes diferentes.

``` console
$ git push -f
Enter passphrase for key '/home/Alan/.ssh/id_rsa':
Counting objects: 21, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (18/18), done.
Writing objects: 100% (21/21), 2.73 KiB | 0 bytes/s, done.
Total 21 (delta 9), reused 5 (delta 1)
To git@github.com:OSMBrasil/IJSN_road_import.git
 + 89aacb0...66822cf master -> master (forced update)
```

Encaremos como sendo "um outro histórico git". Agora são apenas 2.73 KiB.
