### ISSUE TITLE
OSM wiki page for the import?

### ISSUE THREAD

**Issue by vgeorge** [OSMBrasil/IJSN_road_import#6]
Couldn't find a OSM wiki page for this import.

**Comment by Skippern** [comment]
@vgeorge Wiki page and import mailing list will be done when analysing tool is working, and in due time before actual import

**Comment by Skippern** [comment]
[Placeholder page on wiki](http://wiki.openstreetmap.org/wiki/Esp%C3%ADrito_Santo_%28state%29/IJSN_road_import), information to be filled in with links to this repo and all relevant sources

**Comment by Skippern** [comment]
[Wikipage](http://wiki.openstreetmap.org/wiki/Esp%C3%ADrito_Santo_%28state%29/IJSN_road_import) updated and presented
